// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

type User struct {
	ID        string
	FullName  string
	Email     string
	Phone     string
	Password  string
	IsAdmin   bool
	Birthday  int64
	CreatedAt int64
	UpdateAt  int64
}
